spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdd_dev_db?
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update          